# préférences de danses
set skating::gui(pref:dances) {
	"Valse lente" "Tango" "Quickstep" "Valse viennoise" "Slow Foxtrot"
	----
	"Cha Cha" "Rumba" "Jive" "Samba" "Paso Doble"
	----
	"Salsa" "Mambo" "Rock'n Roll"
	----
	"Valse Musette" "Java"
}
set skating::gui(pref:dances:short) {
	"VL" "TA" "QS" "VV" "SF"
	----
	"CC" "RU" "JV" "SA" "PD"
	----
	"S" "M" "RR"
	----
	"VM" "J"
}

array set skating::gui {
	pref:templates		{0 1 2 3 4 5 6 7 8 9}

	pref:template:name:0	{2 Standards}
	pref:template:dances:0	{{Valse lente} Tango}
	pref:template:name:1	{3 Standards}
	pref:template:dances:1	{{Valse lente} Tango Quickstep}
	pref:template:name:2	{4 Standards}
	pref:template:dances:2	{{Valse lente} Tango Quickstep {Valse viennoise}}
	pref:template:name:3	{5 Standards}
	pref:template:dances:3	{{Valse lente} Tango {Slow Foxtrot} Quickstep {Valse viennoise}}

	pref:template:name:4	{2 Latines}
	pref:template:dances:4	{{Cha Cha} Rumba}
	pref:template:name:5	{3 Latines}
	pref:template:dances:5	{{Cha Cha} Rumba Jive}
	pref:template:name:6	{4 Latines}
	pref:template:dances:6	{{Cha Cha} Samba Rumba Jive}
	pref:template:name:7	{5 Latines}
	pref:template:dances:7	{{Cha Cha} Samba Rumba {Paso Doble} Jive}

	pref:template:name:8	{Dix danses (Std + Lat)}
	pref:template:dances:8	{{Valse lente} Tango {Slow Foxtrot} Quickstep {Valse viennoise} {Cha Cha} Samba Rumba {Paso Doble} Jive}
	pref:template:name:9	{Dix danses (Lat + Std)}
	pref:template:dances:9	{{Cha Cha} Samba Rumba {Paso Doble} Jive {Valse lente} Tango {Slow Foxtrot} Quickstep {Valse viennoise}}
}

set ::currentLanguage "french"

# messages
array set msg {
	round:				""
	round:__result__	""

	round:finale		"Finale"
	round:prefinale		"Pre-Finale"
	round:semi			"1/2 Finale"
	round:quarter		"1/4 Finale"
	round:eight			"1/8 Finale"
	round:16			"1/16 Finale"
	round:32			"1/32 Finale"
	round:64			"1/64 Finale"
	round:128			"1/128 Finale"
	round:256			"1/256 Finale"
	round:512			"1/512 Finale"
	round:1024			"1/1024 Finale"
	round:finale.2		""
	round:prefinale.2	""
	round:semi.2		"1/2 Finale (+)"
	round:quarter.2		"1/4 Finale (+)"
	round:eight.2		"1/8 Finale (+)"
	round:16.2			"1/16 Finale (+)"
	round:32.2			"1/32 Finale (+)"
	round:64.2			"1/64 Finale (+)"
	round:128.2			"1/128 Finale (+)"
	round:qualif		"Qualification"

	round:short:			""
	round:short:all			"Tous"
	round:short:finale		"F"
	round:short:prefinale	"PreF"
	round:short:semi		"1/2"
	round:short:quarter		"1/4"
	round:short:eight		"1/8"
	round:short:16			"1/16"
	round:short:32			"1/32"
	round:short:64			"1/64"
	round:short:128			"1/128"
	round:short:256			"1/256"
	round:short:512			"1/512"
	round:short:1024		"1/1024"
	round:short:semi.2		"1/2+"
	round:short:quarter.2	"1/4+"
	round:short:eight.2		"1/8+"
	round:short:16.2		"1/16+"
	round:short:32.2		"1/32+"
	round:short:64.2		"1/64+"
	round:short:128.2		"1/128+"
	round:short:qualif		"Qualif"



	dlg:abort			"Abandonner"
	dlg:retry			"Ressayer"
	dlg:ignore			"Ignorer"
	dlg:ok				"OK"
	dlg:cancel			"Annuler"
	dlg:yes				"Oui"
	dlg:no				"Non"
	dlg:print			"Imprimer"
	dlg:save			"Sauver"
	dlg:saveAs			"Sauver sous ..."
	dlg:saveAsDefault	"Sauver comme paramètres par défault"
	dlg:options			"Options ..."
	dlg:layout			"Mise en page ..."
	dlg:question		"Question"
	dlg:information		"Information"
	dlg:error			"Erreur"
	dlg:modifiedSave	"Les données en cours ont été modifées.\n\nVoulez-vous les enregistrer avant de quitter ?"
	dlg:modifiedDB		"La base de données pour la saisie rapide a été modifiée.\n\nVoulez-vous enregistrer les changements avant de quitter ?"
	dlg:reallyQuit		"Quitter le programme ?"
	dlg:loadDBFailed	"Erreur lors du chargement de la base de données.\n"
	dlg:saveDBFailed	"Impossible de sauver la base de donnée.\n\nVérifiez que le disque n'est pas plein ou protégé en écriture."
	dlg:saveDefaultsFailed "Une erreur est survenue lors de la sauvegarde des paramètres par défaut."
	dlg:dancesReinit	"Retirer cette dance qui est utilisée dans les sélections entraîne la ré-initialisation des notes à partir du round où elle est utilisée.\n\nVoulez-vous continuer ?"
	dlg:dancesReinit2	"Retirer cette dance qui est utilisée dans la finale entraîne la perte des notes entrées pour la finale pour cette danse.\n\nVoulez-vous continuer ?"
	dlg:couplesReinit	"Changer la sélection des couples entraîne la ré-initialisation des notes déjà entrées.\n\nVoulez-vous continuer ?"
	dlg:judgesReinit	"Changer le choix des juges entraîne la ré-initialisation des notes déjà entrées.\n\nVoulez-vous continuer ?"
	dlg:roundModeReinit	"Changer le mode de gestion des rounds entraîne la ré-initialisation des notes déjà entrées.\n\nVoulez-vous continuer ?"
	dlg:notDefined		"Vous devez définir les danses, les couples et les juges avant de sélectionner un round."
	dlg:notSelected		"Vous devez sélectionner les couples dans les rounds précédents."
	dlg:coupleOne		"Le couple"
	dlg:coupleMany		"Les couples"
	dlg:judgeOne		"Le juge"
	dlg:judgeMany		"Les juges"
	dlg:coupleUsed		"Impossible de supprimer le couple utilisé dans :"
	dlg:coupleUseAlias	"Impossible de supprimer ce couple car des alias existent."
	dlg:judgeUsed		"Impossible de supprimer le juge utilisé dans :"
	dlg:removePanel		"Voulez-vous vraiment supprimer le panel "
	dlg:removeTemplate	"Voulez-vous vraiment supprimer le modèle "
	dlg:confirmDelete	"Voulez-vous vraiment supprimer cette compétition ?"
	dlg:confirmDelete2	"Voulez-vous vraiment supprimer les compétition existantes mais déselectionnées ?"
	dlg:confirmDiscard	"Les données en cours ont été modifées.\n\nSi vous continuez, vous perdrez vos modifications."
	dlg:cantOpen		"Impossible d'ouvrir le fichier"
	dlg:cantSave		"Impossible d'enregistrer le fichier"
	dlg:loadTooRecent	"Le fichier que vous avez chargé a été généré par une version plus récente du programme. Certaines données ne seront pas exploitées et seront perdues si vous sauvez le fichier.\n\nMettez à jour la version de votre logiciel (http://laurent.riesterer.free.fr/skating/download.html)."
	dlg:resetRounds		"Les couples pour le round suivant sont déjà définis.\n\nSi vous continuez, les données déjà entrées seront perdus."
	dlg:notImplemented	"Fonction non encore implémentée."
	dlg:langFailed		"Erreur lors du chargement des préférences de langage."
	dlg:prefFailed		"Erreur lors du chargement des préférences utilisateur."
	dlg:templatesFailed	"Erreur lors du chargement des modèles de compétitions."
	dlg:bugReport		"Erreur interne dans le programme.\n\nEnvoyer un message à laurent.riesterer@free.fr, enjoignant le fichier '3s.bugreport' qui se trouve dans le répertoire d'installation du programme."
	dlg:openPrinter		"Impossible d'accéder à l'imprimante."
	dlg:demoMode		"Fichier de licence invalide ou expirée. Le programme fonctionnera en mode d'évaluation (sauvegarde et impression limitées)."
	dlg:demoSave		"Seule la première compétition sera sauvée dans la version d'évaluation.\nConsulter http://laurent.riesterer.free.fr/skating pour enregistrer votre version."
	dlg:demoPrint		"Seule la première page sera imprimée dans la version d'évaluation.\nConsulter http://laurent.riesterer.free.fr/skating pour enregistrer votre version."
	dlg:demoNotAvailable "Non disponible dans la version d'évaluation.\nConsulter http://laurent.riesterer.free.fr/skating pour enregistrer votre version."
	dlg:pleaseWait		"Patientez quelques instants ..."
	dlg:cannotWrite		"Le programme ne peut pas écrire dans '%s'.\n\nVérifier que vous n'êtes pas sur un CD-ROM ou que les permissions sont correctement positionnées."
	dlg:errorWrite		"Le programme n'a pas pu achever la sauvegarde. Vérifier que votre disque ne soit pas plein."
	dlg:errorWriteBackup "Une sauvegarde d'urgence a été sauvée dans '%s'. Merci de la faire parvenir à l'auteur pour analyse."
	dlg:cannotWeb		"Le programme n'a pas pu générer la partie du Web pour '%s'."
	dlg:webDone			"Le site Web a été généré avec succès.\n\nLe page d'index se trouve en \"%s\""
	dlg:panelLocked		"Le panel est utilisé dans des compétitions déjà commencées. On ne peut plus le modifier.\n\nPour apporter des modifications, créer un nouveau panel et ré-affecter ce panel aux compétitions restantes."

	dlg:editdance		"Edition de la danse"
	dlg:editdanceLabel	"Entrez le nom de la danse:"
	dlg:editdanceShortLabel	"Entrez l'abbréviation:"
	dlg:editgroups		"Edition des groupes"

	dlg:plugin			"Choix de plug-in"
	dlg:quickinput		"Saisie rapide"
	dlg:standard		"Mode standard"
	dlg:new:msg			"Vous pouvez créer rapidement des couples et des juges.\nUtilisez les spinboxes ci-dessous."
	dlg:new:couples		"Couples numérotés de"
	dlg:new:couples2	"à"
	dlg:new:judges		"Nombre de juges"

	dlg:print:from		"Imprimer les pages de"
	dlg:print:to		"à"
	dlg:print:all		"tout"
	dlg:print:page		"page courante"

	dlg:OCM:errLogin	"Cannot login to the OCM system"
	dlg:OCM:noHeatId	"No heatID defined for this competition, please regenerate the file"


	setting				"Préférences"
	event				"Evénement"
	eventManagement		"Gestion événement"
	general				"Général"
	attributes			"Attributs"
	dances				"Danses"
	other				"Autre"
	notation			"Système de notation"
	notation:normal		"normal"
	notation:ten		"dix danses"
	notation:qualif		"qualification round"
	notation:tree		"hierarchique"
	templates			"Modèles"
	add:template		"Ajouter\nun modèle"
	remove:template		"Supprimer\nun modèle"
	edit				"Editer ..." 
	load				"Charger ..." 
	save				"Sauver ..."
	search				"Chercher"
	replace				"Remplacer"
	except				"sauf"
	create				"Créer"
	useCountry			"'Pays' au lieu \nde 'Ecole/club'"
	to					"Jusqu'à"
	from				"A partir de"
	remove				"Enlever"
	removeall			"Tout enlever"
	insert:before		"Insérer avant"
	insert:after		"Insérer après"
	numberSorting		"Tri des dossards"
	redisplay			"Réaffichage\n(tri par num.)"
	redisplay2			"Réaffichage\n(tri par lettre)"
	toclip				"Copier tout"
	fromclip			"Coller"
	fromclip2			"Tout enlever\n& coller"
	add:panel			"Ajouter\nun panel"
	remove:panel		"Supprimer\nun panel"
	Couple				"Couple"
	couples				"Couples"
	couples:none		"Aucun couple sélectionné"
	couples:one			"couple sélectionné"
	couples:twoAndMore	"couples sélectionnés"
	couples:among		"couples sur"
	judge				"Juge"
	judges				"Juges"
	Round				"Round"
	rounds				"Rounds"
	roundManagement		"Gestion des rounds"
	selection			"Sélection"
	sortby				"Trier par"
	sortby:number		"numéro"
	sortby:name			"nom"
	sortby:school		"école"
	sortby:country		"pays"
	startingRound		"Round de départ pour "
	startIn				"Round de départ: "
	name				"Nom"
	input				"Saisie"
	deselectAll			"Déselectionner tous les juges"
	all					"Tous"
	none				"Aucun"
	copyFrom			"Copier"
	sameAs				"Mêmes couples que pour ..."
	selectByPanel		"Sélection par les panels"
	getMarksFromOCM		"Récupérer notes OCM"
	couplesToExclude	"Couples à exclure"
	keep				"Prise en compte"
	useInResult			"danse utilisée pour les résultats"
	hint				"Indication"
	Heats				"Heats"
	active				"activées"
	select				"Sélectionnez"
	rescue				"Repêchez"
	among				"couples sur les"
	competing			"en lice"
	remaining			"restants"
	createPreFinale		"Créer une pre-finale"
	result				"Résultat"
	selectionCouples	"Sélection des couples"
	keepCouples			"Couples à reprendre"
	splitCouples1		"Partager en"
	splitCouples2		"groupes"
	splitAdjust	     	"Ajuster"
	nextRound			"Round suivant"
	validation			"Validation"
	force				"Forcer"
	date				"Date"
	title				"Titre"
	comment				"Commentaires"
	attributes			"Attributs"
	attributes:_place	"Lieu"
	attributes:_organizer "Organisateur"
	attributes:_masterCeremony "Maître de cérémonie"
	attributes:_chairman "Chairman"
	attributes:_music	"Musique"
	attributes:_scrutineer "Scrutineer(s)"
	attributes:_support	"Logistique"
	attributes:_member	"Membre IDSF"
	uptodate			"A jour"
	apply				"Appliquer"
	competitions		"Compétitions"
	define				"Définir"
	choose				"Parcourir ..."
	rename				"Renommer"
	choice				"Choix"
	compSelected0		"Aucune compétition sélectionnée (sur %2$d compétitions définies)"
	compSelected1		"%1$d compétition sélectionnée (sur %2$d compétitions définies)"
	compSelected2		"%1$d compétitions sélectionnées (sur %2$d compétitions définies)"


	help:couples:edit	{"Edition d'une cellule:" blue \
						"\tF2, double-clic ou saisie directe (Escape pour annuler)\n" normal \
						"Ajout d'un couple:" blue \
						"\tUtilisez les boutons d'insertion ou allez à la dernière ligne" normal}
	help:couples:error	"ERREUR: numéro de couple déjà utilisé"
	help:couples:alias	"ERREUR: alias impossible car couple racine inexistant"
	help:couples:alias2	"ERREUR: impossible de renommer le couple car il possède des alias"
	help:couples:paste1	"ERREUR: impossible de lire le presse-papier (vide ou format non supporté)"
	help:couples:paste2	"ERREUR: numéros de couples dupliqués dans le presse-papier"
	help:couples:paste3	"ERREUR: numéro de couple du presse papier en conflit"
	help:judges:edit	{"Edition d'une cellule:" blue \
						"\tF2, double-clic ou saisie directe (Escape pour annuler)\n" normal \
						"Enlever un juge:" blue \
						"\tUtilisez les boutons sur la droite" normal}
	help:judges:error	"ERREUR: lettre de juge déjà utilisée"
	help:judges:paste1	"ERREUR: impossible de lire le presse-papier (vide ou format non supporté)"
	help:judges:paste2	"ERREUR: lettre de juges dupliqués dans le presse-papier"
	help:judges:paste3	"ERREUR: lettre de juge du presse papier en conflit"
	help:judges:paste4	"ERREUR: format du juge incorrect : doit être LETTRE + (optionnel) LETTRE ou CHIFFRE"
	help:panels:edit	{"Edition du nom:" blue \
						"\tF2 ou double-clic sur le nom (Escape pour annuler)\n" normal}
	help:templates:edit	{"Edition de la danse:" blue \
						"\tdouble-clic sur le nom (Escape pour annuler)\n" normal \
"Ordre des danses:" blue \
						"\tUtiliser les boutons Haut/Bas\n" normal}
	help:finale			{"Gauche,droite,haut,bas, home et fin" blue \
						"\tdéplacement dans le tableau\n" normal \
						"1 à 9" blue \
						"\tentrée d'une note pour le couple et la danse sélectionnée\n" normal \
						"A à Z" blue \
						"\ttapez la lettre d'un juge pour activer sa zone de saisie" normal}
	help:couples:groups	{"Affecter les couples dans les plages de dossards.\nCliquer sur OK pour réaffecter les dossards par ordre alphabétique à l'intérieur de chaque plage." blue }


	number				"Num."
	name				"Nom"
	man					"Homme"
	lady				"Femme"
	category			"Catégorie"
	school				"Ecole"
	schoolClub			"Ecole/Club"
	country				"Pays"
	letter				"Lettre"
	label				"Intitulé"
	Panel				"Panel"
	Panels				"Panels"
	panel				"panel"
	panels				"panels"
	allJudges			"Tous les juges"
	noJudges			"Aucun juge"

	add					"Ajouter"
	modify				"Modifier"
	merge				"Fusionner"
	clearall			"Effacer tout"
	database			"Bases de données"
	automatic			"Automatique"
	manual				"Manuelle"
	select2				"sélectionner"
	secondChance		"repêchage"
	firstChance			"éliminatoires"
	naming				"Utiliser des noms explicites"
	50%rule				"Forcer 50% des sélectionnés d'un round au suivant"

	newCompetition		"Nouvelle compétition"
	newJudge			"Nouveau juge"
	noName				"sans nom"
	fileDatabase		"Fichiers Skating/Base de données"
	fileSkating			"Fichiers Skating"
	fileSkatingPref		"Fichiers Skating/Préférences"
	fileSkatingSkt		"Fichiers Skating/Modèles"
	fileText			"Fichiers texte"
	filePostscript		"Fichiers Postscript"
	fileImages			"Fichiers images"
	fileLanguage		"Fichiers de langues"
	fileAll				"Tous les fichiers"
	dancesSelection		"Sélection des danses"
	ranking				"Classement"
	rankingFinal		"Classement final"
	byCouple			"Par couple"
	byPlace				"Par place"
	place				"Place"
	best				"Round"
	summary				"Résumé"
	tot					"Tot."
	total				"Total"
	remarks				"Remarques"
	excludedFrom		"Exclus de"
	rule				"Règle"
	print				"Impression"
	couplesAndJudges	"couples & juges"
	judgesOnly			"juges seulements"
	judgesEnrollment	"table juges/compétitions"
	listPanels			"liste des panels"
	listPanels:perRow	"panels par ligne"
	checkEnrollment		"table couples/compétitions pour vérification des participations"
	checkEnrollment:number "par numéro"
	checkEnrollment:alphabetic "par ordre alphabétique"
	checkEnrollment:groupBySchool "grouper d'abord par école/club"
	checkEnrollment:groupByCountry "grouper d'abord par pays"
	checkEnrollment:pageBreak "imprimer chaque école/club sur une page séparée"
	checkEnrollment:pageBreak2 "imprimer chaque pays sur une page séparée"
	checkEnrollment:withResults "imprimer les résultats disponibles"
	competitionsEnrollment "table couples & juges par compétition"
	competitionsEnrollment:judges "imprimer les juges"
	competitionsEnrollment:dances "imprimer les danses"
	competitionsEnrollment:select "imprimer le nombre couples à sélectionner"
	competitionsEnrollment:pageBreak2 "commencer chaque compétition sur une nouvelle page"
	competitionsList	"liste des compétitions"

	resultCompetition	"résultat de la compétition sélectionnée"
	resultFor			"résultats de"
	wholeCompetition	"compétition sélectionnée"
	round				"round sélectionné"
	folderSummary:place	"bilan de la compétition (par place)"
	folderSummary:couple "bilan de la compétition (par couple)"
	forRound			"pour le round"
	summary:place		"bilan par place"
	summary:couple		"bilan par couple"
	dance:place			"chaque danse par place"
	dance:couple		"chaque danse par couple"
	full				"détails pour chaque danse"
	idsf:report			"rapport IDSF"
	idsf:table			"table des résultats IDSF"
	markSheetsLayout	"Mise en page"
	portrait			"portrait"
	landscape			"paysage"
	orientation			"Orientation du papier"
	judgesInSummary		"Impression de la liste des juges dans les résumés"
	judgesInSummary:0	"sur une page séparée"
	judgesInSummary:1	"sur chaque page"
	of					"de"
	printing			"Impression en cours"
	printing:msg		"Compétitions traitées :"
	printing:page		"Impression de la page"
	page				"page"
	pages				"pages"
	marksSheets			"Feuilles pour les juges"
	resultsSheets		"Résultats"
	eventSheets			"Données globales"
	webOutput			"Internet"
	copies				"Nombre de copies"
	print:options		"Options"
	print:rounds		"Imprimer des résultats"
	print:summaries		"Imprimer des bilans récapitulatifs"
	print:all			"Impression pour toutes les compétitions"
	all:rounds 			"détails de tous rounds"
	separateInputGrid	"Zone de saisie séparée pour les numéro"
	yes					"oui"
	yes,				"oui,"
	no					"non"
	heatsGeneration		"Génération automatique des heats"
	heatsIn				"soit"
	heatsSize			"taille"
	heatsSizeDefault	"Taille des heats demandée"
	heatsCouplesGrouping "Mode pour le groupage des couples"
	heatsNumber			"numéro"
	heatsAlphabetic		"alphabétique"
	heatsRandom			"aléatoire"
	heatsMarkingSheets	"Imprimer les feuilles pour les juges"
	heatsPrint?			"Imprimer les feuilles pour les juges avec la liste des heats"
	heatsSheets			"oui"
	heatsNoSheets		"non, juste la liste des couples et des heats"
	heatsPrintLists		"Imprimer les listes pour le round"
	heatsListNone		"aucune"
	heatsListJudges		"juges"
	heatsListDances		"danses"
	heatsListBoth		"juges & danses"
	heatsCompact?		"Imprimer les danses"
	heatsCompact?2		"Imprimer toutes les danses sur une seule page"
	heatsCompact		"toutes sur une page"
	heatsNoCompact		"une danse par page"
	spareBoxes			"Cases supplémentaires"
	spareBoxes1			"Ajouter"
	spareBoxes2			"cases pour entrées de retardataires"
	signSheets			"Signature des feuilles par les juges"
	newSheetOnJudge?	"Imprimer chaque juge"
	newSheetOnJudgeY	"sur une nouvelle feuille"
	newSheetOnJudgeN	"à la suite"
	newSheetOnJudge		"Commencer chaque juge sur une nouvelle feuille"

	web:parameters		"Paramètres"
	web:outputdir		"Répertoire de sortie"
	web:filenameSKA		"Nom du fichier au format .SKA"
	web:filenameZIP		"Nom de l'archive du site généré"
	web:customization	"Personnalisation"
	web:links			"Liens supplémentaires"
	web:links:header	""
	web:links:data		""
	web:email			"Adresse e-mail"
	web:logo			"Logo à insérer dans les pages"
	web:headers			"Répétition des headers"
	web:repeatCouples	"numéro du couple toutes les"
	web:repeatCouples:2	"danses"
	web:repeatHeader	"général tout les"
	web:repeatHeader:2	"couples"
	web:repeatHeaderSummary	"général dans les bilans tout les"
	web:repeatHeaderSummary:2 "couples"
	web:output			"Données à générer"
	web:output:rounds	"rounds & finale"
	web:output:summaries "bilans par couple & place"
	web:output:idsf		"données IDSF"
	web:generating		"Génération du site Web"
	web:generating:msg	"Compétitions traitées :"
	web:generating:page	"Pages générées"


	options:general		"Général"
	options:colors		"Couleurs"
	options:rounds		"Rounds & finale"
	options:print		"Impression"
	options:print2		"Impression (2)"
	options:attributes	"Attributs"
	options:dances		"Danses"
	options:templates	"Modèles"
	options:database	"Base de donnée"
	options:language	"Langue"

	saving				"Sauvegarde"
	saving:backup		"Générer des backups (.bak.ska) lors des enregistrements"
	saving:autosave		"Sauvegarde automatique toutes les"
	saving:autosave2	"minutes (0 pour désactiver)"
	specialmodes		"Modes spéciaux"
	mode:compmgr		"compatibilité CompMgr"
	mode:linkOCM			"liaison avec OCM"
	mode:linkOCM:DBserver	"DB Server"
	mode:linkOCM:DBuser		"DB User"
	mode:linkOCM:DBpassword "DB Password"
	mode:linkOCM:DBdatabase "DB Database"
	mode:linkOCM:server		"OCM Server"
	mode:linkOCM:id			"OCM Scrutinner ID"
	mode:linkOCM:wireless	"utilisation de PDAs"
	mode:linkOCM:DBlogin	"Login DB"
	mode:linkOCM:login		"Login OCM"
	mode:linkOCM:autologin	"Auto-Login"
	colors				"Couleurs"
	other...			"Autre ..."
	colors:finale		"Couleurs dans les finales"
	color:place			"Note correcte"
	color:placebad		"Note en conflit"
	color:exclusion		"Couples exclus (fond)"
	color:exclusion:text "Couples exclus (texte)"
	colors:rounds		"Couleurs des rounds à sélection directe"
	color:choosengood	"Nombre de couples selectionné correct"
	color:choosenprequalif "Couple pré-qualifié"
	color:choosenbad	"Pas assez ou trop de couples"
	colors:general		"Couleurs globales"
	color:competition	"Affichage du round actif"
	color:flash			"Panel ou modèle actif"
	color:lightyellow	"Label horizontal des tableaux"
	color:lightyellow2	"Label horizontal des tableaux alternatif"
	color:yellow		"Label vertical des tableaux"
	color:lightorange	"Label horizontal des tableaux (actif)"
	color:orange		"Label vertical des tableaux (actif)"
	colors:judges		"Couleurs lors de la sélection des juges"
	color:selected		"Juge sélectionné"
	color:notselected	"Juge non sélectionné"
	color:colselected	"Round sélectionné"
	colors:printing		"Couleurs pour l'impression"
	color:print:dark	"couleur titre des tableaux"
	color:print:light	"couleur colonnes des tableaux"
	colors:competition	"Couleurs des compétitions"
	color:activeCompetition	  "Compétition active"
	color:finishedCompetition "Compétition ternimée"
	color:activeDance	"Danse active"
	color:finishedDance	"Danse ternimée"

	names:rounds		"Afficher le noms des juges dans les rounds"
	names:finale		"Afficher le noms des juges dans la finale"
	explain:finale		"Afficher le calcul des classements dans les finales"
	keyboard:toggleling	"Permettre une bascule de sélection par double saisie"
	showNewAtSartup		"Afficher la boite de création rapide au démarrage"
	explicitNames		"Utiliser des noms explicites par défaut"
	explain:ten			"Afficher les règles 10&11 pour classement dix-danses"
	tip:name			"Afficher le nom du couple ou juge en plus de la compétition dans les bulles d'aides lors de la saisie"
	judges:button:compact "Dans les juges, un seul bouton pour une compétition dix danses"

	detailLevel1		"Niveau de détail (général)"
	detail:color		"couleurs dans les tableaux"
	detail:comment		"commentaire associé"
	detail:listCouples	"liste des couples"
	detail:listJudges	"liste des juges"
	detail:order		"trier rounds par total des marks"
	detail:sign			"signatures en bas de page"
	detail:useLetters	"lettres des judges au lieu des X"
	detail:useAverage	"place moyenne au lieu intervalle X-Y"
	detailLevel2		"Niveau de détail (rounds & finale)"
	detail:judges		"noms des juges (round)"
	detail:judgesResult	"noms des juges (finale)"
	detail:couplesResult "noms des couples (finale)"
	detail:useSmallFont	"petite fonte pour couples & juges"
	detail:explain		"explications (règles 10 & 11)"
	detail:place		"place des premiers couples"
	detail:place:nb		"couples à marquer"
	format				"Format"
	graphic				"graphique"
	text				"texte"
	preview				"Aperçu avant impression"
	paper				"Taille du papier"
	margins				"Marges"
	margin:left			"Gauche"
	margin:right		"Droite"
	margin:bottom		"Haut"
	margin:top			"Bas"
	margin:text			"Pour une page en portrait (les marges sont inversées pour un paysage)"
	marksSheetsMode		"Mode des feuilles de marks"
	layout				"Mise en page"
	formatting			"Format des en-têtes"
	formatRestore		"Restaurer les valeurs par défaut"
	format:header		"En-tête principal, ligne"
	format:general		"Ligne générique"
	format:marksheet:portrait:header "En-tête feuille des juges, portrait, ligne"
	format:marksheet:portrait:footer "Pied de page feuille des juges, portrait"
	format:marksheet:landscape:data "Données dans le bandeau, paysage, ligne"
	format:marksheet:landscape:header "En-tête feuille des juges, paysage, ligne"
	format:block:idsf:report "Bloc d'information, rapport IDSF"

	print:title			"Titre"
	print:subtitle		"Sous-titre"
	print:date			"Date"
	print:comment		"Commentaires"
	print:normal		"Normal"
	print:bold			"Gras"
	print:subscript		"Exposant"
	print:small			"Petit texte"
	print:smallbold		"Petit text gras"
	font:folder			"Grand"
	font:title			"Moyen"
	font:date			"Petit"

	attributes:age		"Classe d'age"
	attributes:agemin	"Age minimum"
	attributes:agemax	"Age maximum"
	attributes:ageext	"Age extra info"
	attributes:type		"Discipline"
	attributes:level	"Niveau"
	generateFolderName	"Générer le nom de la compétition"
	folderNaming		"Motif pour la génération du nom de la compétition"

	dances:new			"Nouvelle danse ..."
	dances:edit			"Editer la danse ..."
	dances:separator	"Ajouter un séparateur"
	dances:help			{"<Haut>/<Bas>:" blue \
						"\tSélectionne une danse\n" normal \
						"<Shift>+<Haut>/<Bas>:" blue \
						"\tDéplace la danse\n" normal \
						"<Ins>/<Suppr>:" blue \
						"\tInsert une nouvelle danse / supprime la danse" normal}

	templates:danses	"Modèles pour les ensembles de danses"
	templates:file		"Fichier par défaut pour les modèles de compétitions"

	db:activate			"Activation"
	db:activate:couples	"Activer la complétion pour les couples & les écoles"
	db:activate:judges	"Activer la complétion pour les juges"
	db:file				"Fichier"
	db:filename			"Nom du fichier"
	db:help				{"Pour modifier la base de données, ouvrir le fichier dans un éditeur de texte. Les données sont stockées dans trois variables nommées " normal \
						"judges" blue " pour les juges, " normal \
						"couples" blue " pour les couples et " normal \
						"schools" blue " pour les écoles/clubs.\n\n" normal \
						"Les données sont sauvées par ordre alphabétique pour faciliter l'édition. Toutefois, l'ordre des données dans le fichier n'a aucune importance.\n\n" normal \
						"Les fonctions Export/Import permettent d'enregistrer les données dans des colonnes. Elles peuvent être modifiées sous Excel et ensuite importer.\n\n" normal}
	db:export			"Exporter vers le presse-papier (Copier)"
	db:import			"Importer depuis le presse-papier (Coller)"

	language:language	"Langue"
	language:new		"Nouveau ..."
	language:edit		"Edition"
	language:help		{"Alt+Haut/Bas:" blue \
						"\tSélection de l'élément à traduire précédent/suivant\n" normal}
						

	license:demo		"Version d'évaluation"
	license:registred	"Enregistré pour"
	license:expiry		"Valide jusqu'au"
	license:id			"Numéro d'identification"
	license:maxallowed	"Valide jusqu'à version"


	result:simple		"Résultats globaux"
	result:extended:place "Détail par place"
	result:extended:couple "Détail par couple"
	result:computing	"Calcul des résultats"
	result:computing:msg "Couples traités :"


	prt:general			"Evénement"
	prt:competitions	"Compétitions"
	prt:index			"Accueil"
	prt:rounds			"Rounds"
	prt:round			"Round"
	prt:dances			"Danses"
	prt:dance			"Danse"
	prt:produced		"(c)"
	prt:place			"Place"
	prt:placeFrom		"Place de"
	prt:placeTo			"à"
	prt:place:short		"Plc"
	prt:couple			"Cple"
	prt:final			"Classement final"
	prt:final:dances	"Classement par danse"
	prt:total			"Total"
	prt:selected		"%1$d couples sélectionnés pour %4$s (%2$d demandés)"
	prt:selectedPrequalif "%1$d couples sélectionnés pour %4$s (%2$d demandés, %3$d préqualifiés)"
	prt:explainPrequalif "(%1$d préqualifiés, %2$d couples sur %5$d pour '%6$s')"
	prt:explainPrequalifSplit "(%1$d préqualifiés, %2$d+%3$d=%4$d couples sur %5$d pour '%6$s')"
	prt:rule			"Règle"
	prt:majority		"majorité"
	prt:explainRule		"Application de la règle $nb"
	prt:keep			"$nb repris"
	prt:selNotDone		"sélection non effectuée"
	prt:result			"Résultat"
	prt:resultShort		"Re"
	prt:results			"Résultats"
	prt:resultsFinale	"Résultats de la finale"
	prt:statistics		"Statistiques"
	prt:set				"Qualifiés"
	prt:headerTot		"Tot. Repris"
	prt:roundMaxi		"Meilleur classement atteint par les couples"
	prt:name			"Nom"
	prt:school			"Ecole/Club"
	prt:country			"Pays"
	prt:page			"Page"
	prt:placeAbbrev		"P"
	prt:tot				"Tot."
	prt:class			"Class."
	prt:rules			"Règles"
	prt:yes				"oui"
	prt:keepLabel		"Rep."
	prt:judges			"Juges"
	prt:couples			"Couples"
	prt:couples2		"couples"
	prt:prequalified	"Préqualifiés"
	prt:prequalified2	"préqualifiés"
	prt:couplesNb		"N°"
	prt:scrutineer		"Scrutineer"
	prt:chairman		"Chairman"
	prt:panel			"Panel"
	prt:panels			"Liste des panels de juges"
	prt:enrollment:couples "Participation des couples aux compétitions"
	prt:enrollment:judges "Participation des juges aux compétitions"
	prt:competitions:list "Liste des compétitions"
	prt:summary			"Bilan de la compétition"
	prt:summaryFor		"Bilan pour"
	prt:round			"Rnd"
	prt:heats			"Liste des heats pour le round"
	prt:Heat			"Heat"
	prt:sign			"Signature"
	prt:skipped			"non dansée"
	prt:sumInFinale		"Somme en finale"
	prt:idsf:report		"Rapport de la compétition"
	prt:idsf:table		"Tableau des résultats"

	prt:nbcouples		"Nombres de couples en compétition"
	prt:couplesRegistered "couples enregistrés"
	prt:judgesRegistered "juges enregistrés"
	prt:notAvailable	"Non disponible"
	prt:dataFor3S		"Fichier informatique pour le logiciel 3S"
	prt:siteArchive		"Archive ZIP du site Web"


	tip:new				"Nouveau fichier (Ctrl+N)"
	tip:open			"Ouvrir fichier (Ctrl+O)"
	tip:save			"Sauver fichier (Ctrl+S)"
	tip:print			"Imprimer (Ctrl+P)"
	tip:options			"Réglage des préférences"
	tip:event			"Définition et gestion des couples et des juges (Ctrl+D)"
	tip:comp:new		"Nouvelle compétition (Ctrl+C)\nClick-droit pour les  modèles de compétitions"
	tip:comp:delete		"Suppression compétition (Ctrl+Suppr)"
	tip:comp:moveup		"Déplacer la compétition vers le haut (Ctrl+Up)"
	tip:comp:movedown	"Déplacer la compétition vers le bas (Ctrl+Down)"
	tip:print:result1	"Impression DIRECTE de la liste des heats pour le round suivant"
	tip:print:result2	"Impression DIRECTE de la liste des heats et des feuilles pour les juges pour le round suivant"
	tip:print:result3	"Impression DIRECTE de la liste des couples & des juges pour le round suivant"


	dateFormat			"%d %B %Y"
	months				{Janvier Février Mars Avril Mai Juin Juillet Août Septembre Octobre Novembre Décembre}


	help:rounds 		"Rappel des limites imposées par la FFDS :
	8 couples	-->	1/2 finale
	15 couples	-->	1/4 finale
	29 couples	-->	1/8 finale
	57 couples	-->	1/16 finale
	113 couples	-->	1/32 finale"
}
