# préférences de danses
set skating::gui(pref:dances) {
	"Waltz" "Tango" "Quickstep" "Viennese Waltz" "Slow Foxtrot"
	----
	"Cha Cha" "Rumba" "Jive" "Samba" "Paso Doble"
	----
	"Salsa" "Mambo" "Rock'n Roll"
	----
	"East Coast Swing" "West Coast Swing"
}
set skating::gui(pref:dances:short) {
	"WA" "TA" "QS" "VW" "SF"
	----
	"CC" "RU" "JV" "SA" "PD"
	----
	"SL" "MA" "RR"
	----
	"ECS" "WCS"
}

array set skating::gui {
	pref:templates		{0 1 2 3 4 5 6 7 8 9}

	pref:template:name:0	{2 Ballroom}
	pref:template:dances:0	{Waltz Tango}
	pref:template:name:1	{3 Ballroom}
	pref:template:dances:1	{Waltz Tango Quickstep}
	pref:template:name:2	{4 Ballroom}
	pref:template:dances:2	{Waltz Tango Quickstep {Viennese Waltz}}
	pref:template:name:3	{5 Ballroom}
	pref:template:dances:3	{Waltz Tango {Slow Foxtrot} Quickstep {Viennese Waltz}}

	pref:template:name:4	{2 Latines}
	pref:template:dances:4	{{Cha Cha} Rumba}
	pref:template:name:5	{3 Latines}
	pref:template:dances:5	{{Cha Cha} Rumba Jive}
	pref:template:name:6	{4 Latines}
	pref:template:dances:6	{{Cha Cha} Samba Rumba Jive}
	pref:template:name:7	{5 Latines}
	pref:template:dances:7	{{Cha Cha} Samba Rumba {Paso Doble} Jive}

	pref:template:name:8	{Ten dances (Std + Lat)}
	pref:template:dances:8	{Waltz Tango {Slow Foxtrot} Quickstep {Viennese Waltz} {Cha Cha} Samba Rumba {Paso Doble} Jive}
	pref:template:name:9	{Ten dances (Lat + Std)}
	pref:template:dances:9	{{Cha Cha} Samba Rumba {Paso Doble} Jive Waltz Tango {Slow Foxtrot} Quickstep {Viennese Waltz}}
}

set ::currentLanguage "english"


# messages
array set msg {
	round:				""
	round:__result__	""

	round:finale		"Finale"
	round:prefinale		"Pre-Finale"
	round:semi			"1/2 Finale"
	round:quarter		"1/4 Finale"
	round:eight			"1/8 Finale"
	round:16			"1/16 Finale"
	round:32			"1/32 Finale"
	round:64			"1/64 Finale"
	round:128			"1/128 Finale"
	round:256			"1/256 Finale"
	round:512			"1/512 Finale"
	round:1024			"1/1024 Finale"
	round:finale.2		""
	round:prefinale.2	""
	round:semi.2		"1/2 Finale (+)"
	round:quarter.2		"1/4 Finale (+)"
	round:eight.2		"1/8 Finale (+)"
	round:16.2			"1/16 Finale (+)"
	round:32.2			"1/32 Finale (+)"
	round:64.2			"1/64 Finale (+)"
	round:128.2			"1/128 Finale (+)"
	round:qualif		"Qualification"

	round:short:			""
	round:short:all			"All"
	round:short:finale		"F"
	round:short:prefinale	"PreF"
	round:short:semi		"1/2"
	round:short:quarter		"1/4"
	round:short:eight		"1/8"
	round:short:16			"1/16"
	round:short:32			"1/32"
	round:short:64			"1/64"
	round:short:128			"1/128"
	round:short:256			"1/256"
	round:short:512			"1/512"
	round:short:1024		"1/1024"
	round:short:semi.2		"1/2+"
	round:short:quarter.2	"1/4+"
	round:short:eight.2		"1/8+"
	round:short:16.2		"1/16+"
	round:short:32.2		"1/32+"
	round:short:64.2		"1/64+"
	round:short:128.2		"1/128+"
	round:short:qualif		"Qualification"



	dlg:abort			"Abort"
	dlg:retry			"Retry"
	dlg:ignore			"Ignore"
	dlg:ok				"OK"
	dlg:cancel			"Cancel"
	dlg:yes				"Yes"
	dlg:no				"No"
	dlg:print			"Print"
	dlg:save			"Save"
	dlg:saveAs			"Save as ..."
	dlg:saveAsDefault	"Save as default parameters"
	dlg:options			"Options ..."
	dlg:layout			"Layout ..."
	dlg:question		"Question"
	dlg:information		"Information"
	dlg:error			"Error"
	dlg:modifiedSave	"Some data have been modified.\n\nDo you want to save them before exiting ?"
	dlg:modifiedDB		"The database used for quick entry has been modified.\n\nDo you want to change the modifications before to quit ?"
	dlg:reallyQuit		"Quit the program ?"
	dlg:loadDBFailed	"An error occured while loading the database file. The completion database will be incomplete.\n"
	dlg:saveDBFailed	"Can't save the database.\n\nVerify that the disk is not full or write-protected."
	dlg:saveDefaultsFailed "An error occured while trying to save default parameters."
	dlg:dancesReinit	"Removing this dance which is used in some rounds will reinitialize the notes starting from the first round using it.\n\nDo you want to continue ?"
	dlg:dancesReinit2	"If you remove this dance which is used in the finale, you will loose the notes entered for this dance in the finale.\n\nDo you want to continue ?"
	dlg:couplesReinit	"Modifying the selection of couples will reinitialize the notes already given.\n\nDo you want to continue ?"
	dlg:judgesReinit	"Modifying the selection of adjudicators will reinitialize the notes already given after and including this round.\n\nDo you want to continue ?"
	dlg:roundModeReinit	"Modifying the round management mode will reinitialize the notes already given.\n\nDo you want to continue ?"
	dlg:notDefined		"You must define the danses, the couples and the adjudicators before selecting a round."
	dlg:notSelected		"You must select the couples in the previous rounds."
	dlg:coupleOne		"The couple"
	dlg:coupleMany		"The couples"
	dlg:judgeOne		"The adjudicator"
	dlg:judgeMany		"The adjudicators"
	dlg:coupleUsed		"Cannot suppress this couple used in:"
	dlg:coupleUseAlias	"Cannot suppress this couple because aliases are defined."
	dlg:judgeUsed		"Cannot suppress this adjudicator used in:"
	dlg:removePanel		"Do you really want to suppress the panel "
	dlg:removeTemplate	"Do you really want to suppress the template "
	dlg:confirmDelete	"Do you really want to delete this competition ?"
	dlg:confirmDelete2	"Do you really want to delete the existing competition but currently not selected ?"
	dlg:confirmDiscard	"Some data have been modified.\n\nIf you continue, your modifications will be lost."
	dlg:cantOpen		"Can't open the file"
	dlg:cantSave		"Can't save the file"
	dlg:loadTooRecent	"The file you have loaded has been generated by a more recent version of the program. Some data will not be processed and will be lost if you save the file.\n\nPlease upgrade your program (http://laurent.riesterer.free.fr/skating/download.html)."
	dlg:resetRounds		"The couples for the next round are already defined.\n\nIf you continue, the data for the next round will be lost."
	dlg:notImplemented	"Fonction not implemented yet."
	dlg:langFailed		"Error while loading language preferences."
	dlg:prefFailed		"Error while loading user preferences."
	dlg:templatesFailed	"Error while loading competition templates"
	dlg:bugReport		"Internal error.\n\nPlease send a bug report to laurent.riesterer@free.fr and include the file '3s.bugreport' you will find in the installation directory of the program."
	dlg:openPrinter		"Can't acces to the printer."
	dlg:demoMode		"License file is invalid or has expired. The software will run in evaluation mode (limited saving and printing)."
	dlg:demoSave		"Only the first competition will be saved in this evaluation version.\nPlease go to http://laurent.riesterer.free.fr/skating to register."
	dlg:demoPrint		"Only the first page will be printed in this evaluation version.\nPlease go to http://laurent.riesterer.free.fr/skating to register."
	dlg:demoNotAvailable "Not available in this evaluation version.\nPlease go to http://laurent.riesterer.free.fr/skating to register."
	dlg:pleaseWait		"Please wait ..."
	dlg:cannotWrite		"The program cannot write '%s'.\n\nVerify that this is not a CD-ROM or that the permissions are correct."
	dlg:errorWrite		"The save failed. Please check that your disk is not full."
	dlg:errorWriteBackup "An emergency backup has been saved in '%s'. Please send it to the author to correct the problem."
	dlg:cannotWeb		"An error occured while generating the Web site part for '%s'."
	dlg:webDone			"The Web site was successfully generated.\n\nThe main page is at \"%s\""
	dlg:panelLocked		"This panel is used in some already started competitions. It is locked and can not be modified.\n\nTo change this panel for remaining competitions, create a new one and re-assign it to the competitions."

	dlg:editdance		"Dance edition"
	dlg:editdanceLabel	"Enter the name of the dance:"
	dlg:editdanceShortLabel	"Enter abbreviation:"
	dlg:editgroups		"Groups edition"

	dlg:plugin			"Use plug-in"
	dlg:quickinput		"Quick input"
	dlg:standard		"Standard mode"
	dlg:new:msg			"You can quickly create generic couples and adjudicators.\nUse the spinboxes below:"
	dlg:new:couples		"Number numbered from"
	dlg:new:couples2	"to"
	dlg:new:judges		"Number of adjudicators"

	dlg:print:from		"Print pages from"
	dlg:print:to		"to"
	dlg:print:all		"all"
	dlg:print:page		"current page"

	dlg:OCM:errLogin	"Cannot login to the OCM system"
	dlg:OCM:noHeatId	"No heatID defined for this competition, please regenerate the file"

	setting				"Settings"
	event				"Event"
	eventManagement		"Event management"
	general				"General"
	attributes			"Attributes"
	dances				"Dances"
	other				"Other"
	notation			"Marking system"
	notation:normal		"normal"
	notation:ten		"ten dances"
	notation:qualif		"one qualification round"
	notation:tree		"hierarchical"
	templates			"Templates"
	add:template		"Add\na template"
	remove:template		"Remove\na template"
	edit				"Edit ..." 
	load				"Load ..."
	save				"Save ..."
	search				"Search"
	replace				"Replace"
	except				"except"
	create				"Create"
	useCountry			"'Country' instead \nof 'School/Club'"
	from				"From"
	to					"To"
	remove				"Remove"
	removeall			"Remove all"
	insert:before		"Insert before"
	insert:after		"Insert after"
	numberSorting		"Sort by numbers"
	redisplay			"Redisplay\n(sort by #)"
	redisplay2			"Redisplay\n(sort by letter)"
	toclip				"Copy all"
	fromclip			"Paste"
	fromclip2			"Remove all\n& paste"
	add:panel			"Add\na panel"
	remove:panel		"Remove\na panel"
	Couple				"Couple"
	couples				"Couples"
	couples:none		"No couples selected"
	couples:one			"couple selected"
	couples:twoAndMore	"couples selected"
	couples:among		"couples among"
	judge				"Adjudicator"
	judges				"Adjudicators"
	Round				"Round"
	rounds				"Rounds"
	roundManagement		"Rounds management"
	selection			"Selection"
	sortby				"Sort by"
	sortby:number		"number"
	sortby:name			"name"
	sortby:school		"school"
	sortby:country		"country"
	startingRound		"Starting round for "
	startIn				"Starting round: "
	name				"Name"
	input				"Input"
	deselectAll			"Deselect all the adjudicators"
	all					"All"
	none				"None"
	copyFrom			"Copy"
	sameAs				"Sames couples as for ..."
	selectByPanel		"Selection with the panels"
	getMarksFromOCM		"Get marks from OCM"
	couplesToExclude	"Couples to exclude"
	keep				"Take or skip"
	useInResult			"dance used in result computation"
	hint				"Hint"
	Heats				"Heats"
	active				"active"
	select				"Select"
	rescue				"Keep"
	among				"couples among the"
	competing			"competing"
	remaining			"remaining"
	createPreFinale		"Create Pre-finale"
	result				"Result"
	selectionCouples	"Couples selection"
	keepCouples			"Couples to keep"
	splitCouples1		"Split in"
	splitCouples2		"groups"
	splitAdjust	     	"Adjust"
	nextRound			"Next round"
	validation			"Validation"
	force				"Force"
	date				"Date"
	title				"Title"
	comment				"Comments"
	attributes			"Attributes"
	attributes:_place	"Place"
	attributes:_organizer "Organizer"
	attributes:_masterCeremony "Master of Ceremony"
	attributes:_chairman "Chairman"
	attributes:_music	"Music"
	attributes:_scrutineer "Scrutineer(s)"
	attributes:_support	"Support"
	attributes:_member	"Member"
	uptodate			"Up to date"
	apply				"Apply"
	competitions		"Competitions"
	define				"Define"
	choose				"Choose ..."
	rename				"Rename"
	choice				"Choice"
	compSelected0		"No competition selected (on %2$d defined competitions)"
	compSelected1		"%1$d competition selected (on %2$d defined competitions)"
	compSelected2		"%1$d competitions selected (on %2$d defined competitions)"


	help:couples:edit	{"To edit a cell:" blue \
						"\tdirect input, F2 or double-click on cell (Escape to abort)\n" normal \
						"To add a couple:" blue \
						"\tUse insert buttons or go to last row" normal}
	help:couples:error	"ERROR: duplicate number for couple"
	help:couples:alias	"ERROR: can not create alias because the root couple does not exist"
	help:couples:alias2	"ERROR: can not rename the couple because some aliases are defined"
	help:couples:paste1	"ERREUR: cannot read the clipboard (empty or unsupported format)"
	help:couples:paste2	"ERREUR: couples' numbers duplicated in the clipboard"
	help:couples:paste3	"ERREUR: conflicting number between table and clipboard"
	help:judges:edit	{"To edit a cell:" blue \
						"\tdirect input, F2 or double-click on cell (Escape to cancel)\n" normal \
						"Remove an adjudicator:" blue \
						"\tUse the buttons on the right" normal}
	help:judges:error	"ERREUR: adjudicator's letter already used"
	help:judges:paste1	"ERREUR: cannot read the clipboard (empty or unsupported format)"
	help:judges:paste2	"ERREUR: adjudicators' letters duplicated in the clipboard"
	help:judges:paste3	"ERREUR: conflicting letter between table and clipboard"
	help:judges:paste4	"ERREUR: wrong adjudicator format : should be LETTER + (optional) LETTER or NUMBER"
	help:panels:edit	{"Edit name:" blue \
						"\tF2 or double-click on cell (Escape to cancel)\n" normal}
	help:templates:edit	{"Edit dance's name:" blue \
						"\tdouble-click on the name (Escape to cancel)\n" normal \
"Dances order:" blue \
						"\tUse Up/Down buttons\n" normal}
	help:finale			{"Left,right,up,down, home and end" blue \
						"\tmoves in the table\n" normal \
						"1 to 9" blue \
						"\tinputs a note for the current couple and dance\n" normal \
						"A to Z" blue \
						"\tPress the letter of the judge to active it" normal}
	help:couples:groups	{"Affect each couple in a number range.\nClick OK to give number in respect to the alphabetical order in each group (a group by numbers range)." blue }


	number				"Num."
	name				"Name"
	man					"Man"
	lady				"Lady"
	category			"Category"
	school				"School"
	schoolClub			"School/Club"
	country				"Country"
	letter				"Letter"
	label				"Label"
	Panel				"Panel"
	Panels				"Panels"
	panel				"panel"
	panels				"panels"
	allJudges			"All adjudicators"
	noJudges			"No adjudicators"

	add					"Add"
	modify				"Modify"
	merge				"Merge"
	clearall			"Clear all"
	database			"Database"
	automatic			"Automatic"
	manual				"Manual"
	select2				"select"
	secondChance		"second chance"
	firstChance			"first chance"
	naming				"Use explicits names"
	50%rule				"Force 50% of selected couples from one round to the next"

	newCompetition		"New competition"
	newJudge			"New adjudicator"
	noName				"unknown"
	fileDatabase		"Skating/Database files"
	fileSkating			"Skating files"
	fileSkatingSkt		"Skating/Templates files"
	fileSkatingPref		"Skating/Pref files"
	fileText			"Text files"
	filePostscript		"Postscript files"
	fileImages			"Images files"
	fileLanguage		"Language file"
	fileAll				"All files"
	dancesSelection		"Dances selection"
	ranking				"Ranking"
	rankingFinal		"Final ranking"
	byCouple			"By couple"
	byPlace				"By place"
	place				"Place"
	best				"Round"
	summary				"Summary"
	tot					"Tot."
	total				"Total"
	remarks				"Remarks"
	excludedFrom		"Excluded of"
	rule				"Rule"
	print				"Printing"
	couplesAndJudges	"couples & adjudicators"
	judgesOnly			"adjudicators only"
	judgesEnrollment	"table judges/competitions"
	listPanels			"list of panels"
	listPanels:perRow	"panels per row"
	checkEnrollment		"table showing couples/competitions to check enrollment"
	checkEnrollment:number "by number"
	checkEnrollment:alphabetic "by alphabetical order"
	checkEnrollment:groupBySchool "group by school/club first"
	checkEnrollment:groupByCountry "group by country first"
	checkEnrollment:pageBreak "start each school/club on a new page"
	checkEnrollment:pageBreak2 "start each country on a new page"
	checkEnrollment:withResults "print the results when available"
	competitionsEnrollment "table showing couples & judges for each competition"
	competitionsEnrollment:judges "print judges"
	competitionsEnrollment:dances "print dances"
	competitionsEnrollment:select "print number of couples to select"
	competitionsEnrollment:pageBreak2 "start each competition on a new page"
	competitionsList	"competitions list"

	resultCompetition	"results for the selected competition"
	resultFor			"results for"
	wholeCompetition	"selected competition"
	round				"selected round"
	folderSummary:place	"competition summary (by place)"
	folderSummary:couple "competition summary (by couple)"
	forRound			"for round"
	summary:place		"summary by place"
	summary:couple		"summary by couple"
	dance:place			"each dance by place"
	dance:couple		"each dance by couple"
	full				"details for each dance"
	idsf:report			"IDSF report"
	idsf:table			"IDSF table of results"
	markSheetsLayout	"Layout"
	portrait			"portrait"
	landscape			"landscape"
	orientation			"Paper orientation"
	judgesInSummary		"Printing of adjudicators list in summaries"
	judgesInSummary:0	"on a separate sheet"
	judgesInSummary:1	"on each sheet"
	of					"of"
	printing			"Printing"
	printing:msg		"Competitions processed :"
	printing:page		"Printing page"
	page				"page"
	pages				"pages"
	marksSheets			"Jugdes' sheets"
	resultsSheets		"Results"
	eventSheets			"Global data"
	webOutput			"Internet"
	copies				"Copies"
	print:options		"Options"
	print:rounds		"Results printing"
	print:summaries		"Summaries printing"
	print:all			"Printing of all the competitions"
	all:rounds 			"details for all the rounds"
	separateInputGrid	"Separate input grid for the number"
	yes					"yes"
	yes,				"yes,"
	no					"no"
	heatsGeneration		"Automatic heats generation"
	heatsIn				"in"
	heatsSize			"size"
	heatsSizeDefault	"Default size for heats"
	heatsCouplesGrouping "Couples grouping mode"
	heatsNumber			"number"
	heatsAlphabetic		"alphabetic"
	heatsRandom			"random"
	heatsMarkingSheets	"Print adjusticators' sheets"
	heatsPrint?			"Print adjusticators' sheets with the heats list"
	heatsSheets			"yes"
	heatsNoSheets		"no, just couples & heats"
	heatsPrintLists		"Print of lists for the round"
	heatsListNone		"none"
	heatsListJudges		"adjudicators"
	heatsListDances		"dances"
	heatsListBoth		"adjudicators & dances"
	heatsCompact?		"Print the dances"
	heatsCompact?2		"Print the all dances on one page"
	heatsCompact		"all on one page"
	heatsNoCompact		"one dance per page"
	spareBoxes			"Extra boxes"
	spareBoxes1			"Add"
	spareBoxes2			"extra boxes for late entries"
	signSheets			"Adjudicators must sign the mark sheets"
	newSheetOnJudge?	"Print each judge"
	newSheetOnJudgeY	"on a new sheet"
	newSheetOnJudgeN	"after the last one"
	newSheetOnJudge		"Start each judge on a new sheet"


	web:parameters		"Parameters"
	web:outputdir		"Output directory"
	web:customization	"Customization"
	web:filenameSKA		"Format .SKA filename"
	web:filenameZIP		"Web site archive filename"
	web:links			"Additional links"
	web:links:header	""
	web:links:data		""
	web:email			"e-mail address"
	web:logo			"Logo to insert in the pages"
	web:headers			"headers repeat"
	web:repeatCouples	"couple's number every"
	web:repeatCouples:2	"dances"
	web:repeatHeader	"main header every"
	web:repeatHeader:2	"couples"
	web:repeatHeaderSummary	"main header in summaries every"
	web:repeatHeaderSummary:2 "couples"
	web:output			"Data to output"
	web:output:rounds	"rounds & finale"
	web:output:summaries "summaries by couple & place"
	web:output:idsf		"IDSF data"
	web:generating		"Generating Web site"
	web:generating:msg	"Competitions processed :"
	web:generating:page	"Pages generated"


	options:general		"General"
	options:colors		"Colors"
	options:rounds		"Rounds & finale"
	options:print		"Printing"
	options:print2		"Printing (2)"
	options:attributes	"Attributes"
	options:dances		"Dances"
	options:templates	"Templates"
	options:database	"Database"
	options:language	"Language"

	saving				"Saving"
	saving:backup		"Generate backups (.bak.ska) when saving"
	saving:autosave		"Auto save every"
	saving:autosave2	"minutes (0 to desactivate)"
	specialmodes		"Special modes"
	mode:compmgr		"CompMgr mode"
	mode:linkOCM			"OCM link"
	mode:linkOCM:DBserver	"DB Server"
	mode:linkOCM:DBuser		"DB User"
	mode:linkOCM:DBpassword "DB Password"
	mode:linkOCM:DBdatabase "DB Database"
	mode:linkOCM:server		"OCM Server"
	mode:linkOCM:id			"OCM Scrutinner ID"
	mode:linkOCM:wireless	"use of PDAs"
	mode:linkOCM:DBlogin	"Login DB"
	mode:linkOCM:login		"Login OCM"
	mode:linkOCM:autologin	"Auto-Login"
	colors				"Colors"
	other...			"Other ..."
	colors:finale		"Colors in the finales"
	color:place			"Mark is correct"
	color:placebad		"Mark is in conflict"
	color:exclusion		"Excluded couples (background)"
	color:exclusion:text "Excluded couples (text)"
	colors:rounds		"Colors for rounds with direct selection"
	color:choosengood	"Correct numbre of selected couples"
	color:choosenprequalif "Prequalified couple"
	color:choosenbad	"Not enough or too much selected couples"
	colors:general		"Global colors"
	color:competition	"Active round display"
	color:flash			"Active template or panel"
	color:lightyellow	"Horizontal label for tables"
	color:lightyellow2	"Horizontal label for alternates tables"
	color:yellow		"Vertical label for tables"
	color:lightorange	"Horizontal label for tables (active)"
	color:orange		"Vertical label for tables (active)"
	colors:judges		"Color when selecting adjudicators"
	color:selected		"Selected adjudicator"
	color:notselected	"Non selected adjudicator"
	color:colselected	"Selected round"
	colors:printing		"Colors for printing"
	color:print:dark	"tables header color"
	color:print:light	"tables column color"
	colors:competition	"Colors for competitions"
	color:activeCompetition	  "Active competition"
	color:finishedCompetition "Finished competition"
	color:activeDance	"Active dance"
	color:finishedDance	"Finished dance"
	language:language	"Language"
	language:new		"New ..."
	language:edit		"Edition"
	language:help		{"Alt+Up/Down:" blue \
						"\tSelect to previous/next item to translate\n" normal}


	names:rounds		"Display adjudicators' names in rounds"
	names:finale		"Display adjudicators' names in finales"
	explain:finale		"Display ranking computation in finales"
	keyboard:toggleling	"Allow double input to toggle couple number"
	showNewAtSartup		"Show quick create dialog at startup"
	explicitNames		"Use explicit names by default"
	explain:ten			"explanations (rules 10 & 11) for 10-dances results"
	tip:name			"print the couple or judge name in the tip in the input zone"
	judges:button:compact "in 'adjudicators', one unique button for 10-dances competitions"

	detailLevel1		"Detail level (general)"
	detail:color		"colors in tables"
	detail:comment		"associated comment"
	detail:listCouples	"couples list"
	detail:listJudges	"adjudicators list"
	detail:order		"order rounds by total of marks"
	detail:sign			"signatures"
	detail:useLetters	"adjudicators' letter instead of X"
	detail:useAverage	"average place instead of X-Y"
	detailLevel2		"Detail level (rounds & finale)"
	detail:judges		"adjudicators' names (rounds)"
	detail:judgesResult	"adjudicators' names (finale)"
	detail:couplesResult "couples' names (finale)"
	detail:useSmallFont	"small font for couples & adjudicators"
	detail:explain		"explanations (rules 10 & 11)"
	detail:place		"place of the first couples"
	detail:place:nb		"couples to mark"
	format				"Format"
	graphic				"graphic"
	text				"text"
	preview				"preview"
	paper				"Paper size"
	margins				"Margins"
	margin:left			"Left"
	margin:right		"Right"
	margin:bottom		"Top"
	margin:top			"Bottom"
	margin:text			"For a portrait orientation (margins are swapped for using landscape orientation)"
	marksSheetsMode		"Marks sheets mode"
	layout				"Layout"
	formatting			"Header format"
	formatRestore		"Restore default values"
	format:header		"Main header, line"
	format:general		"Generic line"
	format:marksheet:portrait:header "Marksheet header, portrait, line"
	format:marksheet:portrait:footer "Marksheet footer, portrait"
	format:marksheet:landscape:data "Top zone, landscape, ligne"
	format:marksheet:landscape:header "Marksheet header, landscape, line"
	format:block:idsf:report "Information block, IDSF report"

	print:title			"Title"
	print:subtitle		"Sub-title"
	print:date			"Date"
	print:comment		"Comments"
	print:normal		"Normal"
	print:bold			"Bold"
	print:subscript		"Superscript"
	print:small			"Small text"
	print:smallbold		"Small bold text"
	font:folder			"Large"
	font:title			"Medium"
	font:date			"Small"

	attributes:age		"Age class"
	attributes:agemin	"Minimal age"
	attributes:agemax	"Maximal age"
	attributes:ageext	"Extra info age"
	attributes:type		"Discipline"
	attributes:level	"Level"
	generateFolderName	"Competition name auto-generate"
	folderNaming		"Pattern used to generate the competition name"

	dances:new			"New dance ..."
	dances:edit			"Edit dance ..."
	dances:separator	"Add a separator"
	dances:help			{"<Up>/<Down>:" blue \
						"\tSelect a dance\n" normal \
						"<Shift>+<Up>/<Down>:" blue \
						"\tMove the dance\n" normal \
						"<Ins>/<Del>:" blue \
						"\tInsert a new dance / delete the dance" normal}

	templates:danses	"Danses set templates"
	templates:file		"Default file for competitions templates"

	db:activate			"Activate"
	db:activate:couples	"Activate completion for couples & schools"
	db:activate:judges	"Activate completion for jugdes"
	db:file				"File"
	db:filename			"Filename"
	db:help				{"To modify the database, open the file with a text editor. The data are stored into three variables called " normal \
						"judges" blue " for the adjudicators' names, " normal \
						"couples" blue " for the couples' names and " normal \
						"schools" blue " for the schools/clubs.\n\n" normal \
						"The data are saved in alphabatical order to ease the edition. However, the order of the data in the file does not matter.\n\n" normal \
						"Export/Import allow you to save the data in columns. Theses data can be modified with Excel and then imported.\n\n" normal}
	db:export			"Export to clipboard (Copy)"
	db:import			"Import from clipboard (Paste)"



	license:demo		"Evaluation version"
	license:registred	"Registered to"
	license:expiry		"Valid until"
	license:id			"Unique ID number"
	license:maxallowed	"Valid up to version"


	result:simple		"Global results"
	result:extended:place "Details by place"
	result:extended:couple "Details by couple"
	result:computing	"Computing results"
	result:computing:msg "Couples processed :"


	prt:general			"Event"
	prt:competitions	"Competitions"
	prt:index			"Home"
	prt:rounds			"Rounds"
	prt:dances			"Dances"
	prt:dance			"Dance"
	prt:produced		"Produced with"
	prt:place			"Place"
	prt:placeFrom		"Place from"
	prt:placeTo			"to"
	prt:place:short		"Plc"
	prt:couple			"Cple"
	prt:final			"Final ranking"
	prt:final:dances	"Ranking by dance"
	prt:total			"Total"
	prt:selected		"%1$d couples selected for %4$s (%2$d asked)"
	prt:selectedPrequalif "%1$d couples selected for %4$s (%2$d asked, %3$d prequalified)"
	prt:explainPrequalif "(%1$d prequalified, %2$d couples among %5$d for '%6$s')"
	prt:explainPrequalifSplit "(%1$d prequalified, %2$d+%3$d=%4$d couples among %5$d for '%6$s')"
	prt:rule			"Rule"
	prt:majority		"majority"
	prt:explainRule		"Use of rule $nb"
	prt:keep			"$nb kept"
	prt:selNotDone		"no selection done"
	prt:result			"Result"
	prt:resultShort		"Re"
	prt:results			"Results"
	prt:resultsFinale	"Finale Results"
	prt:statistics		"Statistics"
	prt:set				"Couples set"
	prt:headerTot		"Tot. Kept"
	prt:roundMaxi		"Best round reached by the couples"
	prt:name			"Name"
	prt:school			"School/Club"
	prt:country			"Pays"
	prt:page			"Page"
	prt:placeAbbrev		"P"
	prt:tot				"Tot."
	prt:class			"Rank."
	prt:rules			"Rules"
	prt:yes				"yes"
	prt:keepLabel		"Kept"
	prt:judges			"Adjudicators"
	prt:couples			"Couples"
	prt:couples2		"couples"
	prt:prequalified	"Prequalified"
	prt:prequalified2	"prequalified"
	prt:couplesNb		"#"
	prt:scrutineer		"Scrutineer"
	prt:chairman		"Chairman"
	prt:panel			"Panel"
	prt:panels			"List of adjudicators panels"
	prt:enrollment:couples "Enrollment of the couples for the competitions"
	prt:enrollment:judges "Enrollment of the judges for the competitions"
	prt:competitions:list "Competitions list"
	prt:summary			"Competition summary"
	prt:summaryFor		"Summary for"
	prt:round			"Rnd"
	prt:heats			"Heat list for the round"
	prt:Heat			"Heat"
	prt:sign			"Sign"
	prt:skipped			"skipped"
	prt:sumInFinale		"Sum of places in final"
	prt:idsf:report		"Competition Report"
	prt:idsf:table		"Table of Results"

	prt:nbcouples		"Number of couples in competition"
	prt:couplesRegistered "registered couples"
	prt:judgesRegistered "registered adjudicators"
	prt:notAvailable	"Not available"
	prt:dataFor3S		"Raw file for use with 3S software"
	prt:siteArchive		"Web site ZIP archive"


	tip:new				"New file (Ctrl+N)"
	tip:open			"Open file (Ctrl+O)"
	tip:save			"Save file (Ctrl+S)"
	tip:print			"Print (Ctrl+P)"
	tip:options			"User settings & customization"
	tip:event			"Definition and management of couples and juges (Ctrl+D)"
	tip:comp:new		"New competition (Ctrl+C)"
	tip:comp:delete		"Delete competition (Ctrl+Suppr)"
	tip:comp:moveup		"Move competition upwards (Ctrl+Up)"
	tip:comp:movedown	"Move competition downwards (Ctrl+Down)"
	tip:print:result1	"DIRECT printing of couples heats for the next round"
	tip:print:result2	"DIRECT printing of couples heats & mark sheets for the next round"
	tip:print:result3	"DIRECT printing of couples & judges for the next round"


	dateFormat			"%B %d, %Y"
	months				{January February March April May June July August September October November December}

	help:rounds 		""
}
